language:
  - swift
osx_image: xcode10.1
branches:
  only:
    - master
before_install:
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
  - gem install xcov --pre --no-rdoc --no-ri --no-document --quiet
script:
  - pod lib lint
  - swift build
  - swift test
after_success:
  - xcov -w UInt256.xcworkspace -s UInt256
