language: objective-c
osx_image: xcode9.2
branches:
  only:
    - master
before_install:
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
script:
  - pod lib lint
  - swift build
  - swift test
